import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: { absolute: "Gananza | Política de privacidad" }, description: "Conocé cómo Gananza recopila, utiliza, almacena y protege los datos personales relacionados con cuentas, tareas, recompensas y retiros." };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Información legal" title="Política de privacidad" intro="Esta política explica qué información trata Gananza, para qué la utiliza y qué opciones tienen los usuarios sobre sus datos." updatedAt="2 de agosto de 2026" sections={[
    { id: "alcance", title: "Alcance", content: <p>Esta política se aplica a los datos tratados al acceder a Gananza, crear una cuenta, participar en tareas, consultar recompensas, solicitar retiros o comunicarse con Soporte.</p> },
    { id: "datos", title: "Datos recopilados", content: <><p>Podemos tratar datos de identificación y contacto, información del perfil, datos necesarios para retiros, preferencias, actividad en tareas, estados de validación, movimientos de recompensas, mensajes de soporte e información técnica básica del dispositivo y la sesión.</p><p>No solicitamos que compartas contraseñas de servicios de terceros mediante formularios de soporte.</p></> },
    { id: "autenticacion", title: "Autenticación y cuenta", content: <p>Gananza utiliza Supabase para funciones de autenticación y gestión segura de sesiones. Esto puede implicar el tratamiento de identificadores de usuario, correo electrónico, credenciales protegidas, tokens de sesión y registros técnicos necesarios para mantener el acceso y prevenir usos no autorizados.</p> },
    { id: "cookies", title: "Cookies y tecnologías similares", content: <><p>La plataforma puede utilizar cookies o almacenamiento local estrictamente necesarios para iniciar sesión, conservar la sesión, recordar preferencias y mantener la seguridad. También pueden emplearse datos técnicos para entender el funcionamiento del servicio y corregir errores.</p><p>Podés administrar ciertas tecnologías desde tu navegador, aunque bloquear las necesarias puede impedir el acceso a funciones de la cuenta.</p></> },
    { id: "uso", title: "Uso de la información", content: <p>Utilizamos los datos para operar la cuenta, mostrar tareas pertinentes, registrar participación, seguir validaciones, calcular recompensas, procesar retiros, responder consultas, prevenir fraude, mejorar la plataforma y cumplir obligaciones aplicables.</p> },
    { id: "proveedores", title: "Información enviada a proveedores", content: <><p>Cuando iniciás una oferta, Gananza puede enviar o asociar con el proveedor la información mínima necesaria para atribuir y validar la acción, como un identificador de usuario o participación, campaña, fecha, estado, dispositivo o parámetros técnicos de seguimiento.</p><p>Los proveedores pueden aplicar sus propias políticas de privacidad cuando accedés a sus sitios o servicios. Gananza no les entrega tu contraseña.</p></> },
    { id: "supabase", title: "Almacenamiento y Supabase", content: <><p>Gananza utiliza infraestructura de Supabase para almacenar y consultar información de cuentas y operaciones. Se aplican controles de acceso, autenticación y reglas de seguridad para limitar el acceso según la función y la cuenta correspondiente.</p><p>También pueden intervenir proveedores de infraestructura, alojamiento o comunicaciones cuando resulten necesarios para prestar el servicio.</p></> },
    { id: "proteccion", title: "Protección de datos", content: <><p>Aplicamos medidas técnicas y organizativas razonables orientadas a proteger la confidencialidad, integridad y disponibilidad de la información. Ningún sistema es completamente infalible, por lo que también recomendamos utilizar credenciales únicas y avisar ante cualquier actividad no reconocida.</p><p>Gananza no afirma contar con certificaciones de seguridad que no hayan sido obtenidas formalmente.</p></> },
    { id: "conservacion", title: "Conservación", content: <><p>Los datos se conservan durante el tiempo necesario para prestar el servicio, mantener registros de recompensas y retiros, resolver disputas, prevenir fraude y cumplir obligaciones legales. Los plazos pueden variar según el tipo de información y el estado de la cuenta.</p><p>Cuando los datos dejan de ser necesarios, se eliminan o anonimizan de acuerdo con criterios operativos y legales aplicables.</p></> },
    { id: "derechos", title: "Derechos del usuario", content: <><p>Podés solicitar información sobre tus datos, su actualización, corrección o eliminación cuando corresponda. También podés consultar sobre el tratamiento o retirar consentimientos que se basen en esa autorización, sin afectar tratamientos anteriores legítimos.</p><p>Algunas solicitudes pueden requerir verificación de identidad y ciertos datos podrían conservarse cuando exista una obligación legal, una operación pendiente o una necesidad legítima de seguridad.</p></> },
    { id: "cambios", title: "Cambios en esta política", content: <p>Podemos actualizar esta política por cambios técnicos, operativos o legales. Las modificaciones relevantes se comunicarán mediante medios razonables y la fecha vigente permanecerá publicada en esta página.</p> },
    { id: "contacto", title: "Contacto", content: <p>Para ejercer derechos o realizar consultas sobre privacidad, utilizá la página de <a href="/soporte">Soporte</a> e indicá que tu solicitud se relaciona con datos personales. No incluyas contraseñas ni información sensible innecesaria.</p> },
  ]} />;
}
