import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: { absolute: "Gananza | Términos" }, description: "Conocé los términos y condiciones de uso de Gananza, incluidos los criterios aplicables a tareas, recompensas, validaciones y retiros." };

export default function TermsPage() {
  return <LegalPage eyebrow="Información legal" title="Términos y condiciones" intro="Estos términos regulan el acceso y el uso de Gananza. Te recomendamos leerlos antes de crear una cuenta o participar en una tarea." updatedAt="2 de agosto de 2026" sections={[
    { id: "introduccion", title: "Introducción", content: <><p>Gananza es una plataforma que permite descubrir y completar tareas, encuestas, pruebas de productos u otras oportunidades ofrecidas por Gananza o por proveedores externos. Al acceder o utilizar la plataforma, aceptás estos términos y las políticas relacionadas que resulten aplicables.</p><p>Si no estás de acuerdo con estas condiciones, no debés utilizar Gananza.</p></> },
    { id: "uso-plataforma", title: "Uso de la plataforma", content: <p>Debés utilizar Gananza de manera lícita, personal y respetando las instrucciones de cada tarea. No podés interferir con el funcionamiento de la plataforma, automatizar acciones no autorizadas, manipular atribuciones ni intentar obtener recompensas sin cumplir las condiciones informadas.</p> },
    { id: "elegibilidad", title: "Elegibilidad", content: <p>Para utilizar Gananza debés tener capacidad legal suficiente conforme a las normas aplicables y cumplir los requisitos de edad, ubicación y perfil indicados para cada oportunidad. Algunas tareas pueden estar limitadas por cupos, territorio, dispositivo u otros criterios definidos por el proveedor.</p> },
    { id: "cuenta", title: "Cuenta del usuario", content: <><p>La información de registro debe ser verdadera, completa y mantenerse actualizada. Sos responsable de preservar la confidencialidad de tus credenciales y de la actividad realizada desde tu cuenta. Cada persona debe operar una única cuenta, salvo autorización expresa de Gananza.</p><p>Ante un acceso no reconocido, debés informarlo mediante Soporte.</p></> },
    { id: "recompensas", title: "Recompensas", content: <><p>La recompensa, sus condiciones y su estado se muestran antes o durante la participación. <strong>Gananza no garantiza ingresos, montos mínimos ni disponibilidad permanente de tareas.</strong> Las recompensas dependen de completar y validar correctamente cada tarea.</p><p>Los importes y la disponibilidad pueden variar según la campaña, el perfil, la ubicación, los cupos y las condiciones del proveedor.</p></> },
    { id: "validacion", title: "Validación de tareas", content: <><p>La finalización de una acción no implica acreditación automática. Gananza o el proveedor pueden verificar el cumplimiento, la atribución, la identidad, los plazos y las demás condiciones informadas. Las conversiones incompletas, duplicadas, manipuladas o inválidas pueden ser rechazadas por el proveedor.</p><p>El estado pendiente puede mantenerse durante el plazo necesario para completar esa revisión.</p></> },
    { id: "retiros", title: "Retiros", content: <><p>Solo puede solicitarse el retiro del saldo que figure como disponible. Los retiros están sujetos a verificación de identidad, titularidad, método de pago, límites operativos y controles de seguridad. Los tiempos de acreditación pueden variar según el método elegido y la entidad receptora.</p><p>Gananza puede detener temporalmente una solicitud cuando sea necesario verificar datos o investigar una inconsistencia.</p></> },
    { id: "fraude", title: "Suspensión por fraude", content: <><p>El uso de datos falsos, cuentas múltiples, automatizaciones, manipulación de seguimiento, suplantación de identidad o cualquier intento de obtener recompensas indebidamente puede generar el rechazo de operaciones, la suspensión preventiva o el cierre de la cuenta.</p><p>Cuando corresponda, Gananza podrá conservar la información necesaria para investigar el incidente y cumplir obligaciones legales.</p></> },
    { id: "propiedad", title: "Propiedad intelectual", content: <p>La marca Gananza, su software, diseño, textos, logotipos y componentes propios están protegidos por las normas aplicables. Las marcas y materiales de proveedores pertenecen a sus respectivos titulares. El uso de la plataforma no otorga derechos sobre esos contenidos.</p> },
    { id: "responsabilidad", title: "Limitación de responsabilidad", content: <><p>Gananza procura mantener información clara y un servicio disponible, pero no asegura que todas las tareas permanezcan activas ni que los servicios de terceros funcionen sin interrupciones. Dentro de los límites permitidos por la ley, Gananza no responde por incumplimientos atribuibles a proveedores, entidades financieras, conexiones del usuario o hechos fuera de su control razonable.</p><p>Nada de estos términos limita derechos irrenunciables que correspondan al usuario.</p></> },
    { id: "cambios", title: "Cambios en el servicio", content: <p>Gananza puede actualizar funciones, requisitos o estos términos para reflejar cambios operativos, técnicos o legales. Cuando el cambio sea relevante, se comunicará por medios razonables dentro de la plataforma. La fecha de actualización estará visible en esta página.</p> },
    { id: "contacto", title: "Contacto", content: <p>Las consultas sobre estos términos, una tarea, una recompensa o un retiro pueden enviarse mediante la página de <a href="/soporte">Soporte</a>. Para ayudarnos a identificar el caso, incluí la información necesaria sin compartir contraseñas ni credenciales.</p> },
  ]} />;
}
