import { AppShell } from "@/components/AppShell";
import { getAppContext, getCatalogTasks } from "@/lib/gananza/server-data";

export default async function MyGananzaPage() {
  const [context, tasks] = await Promise.all([getAppContext(), getCatalogTasks()]);
  const confirmed = tasks.filter((task) => task.status === "confirmed").length;
  const progress = Math.min(100, Math.round((context.profile.experiencePoints % 5000) / 50));
  return <AppShell active="/mi-gananza"><section className="page-content"><div className="v3-page-heading"><div><span className="eyebrow">TU PROGRESO</span><h1>Mi Gananza</h1><p>Tu nivel, racha y actividad acumulada.</p></div></div><div className="level-hero"><article className="level-card"><span className="eyebrow" style={{color:"var(--purple-2)"}}>NIVEL {context.profile.level}</span><h2>Seguí completando tareas válidas.</h2><p>Los puntos y beneficios se podrán configurar desde el panel cuando se defina el modelo final.</p><div className="level-bar"><span style={{width:`${progress}%`}} /></div><div className="level-meta"><span><b>{context.profile.experiencePoints.toLocaleString("es-AR")}</b> de 5.000 puntos</span><span>{progress}%</span></div></article><div className="level-benefits"><article className="benefit-card"><span className="benefit-icon green">↗</span><div><strong>Historial auditable</strong><small>Cada cambio financiero genera un movimiento.</small></div></article><article className="benefit-card"><span className="benefit-icon purple">★</span><div><strong>Estados transparentes</strong><small>Pendiente, confirmado, rechazado o revertido.</small></div></article><article className="benefit-card"><span className="benefit-icon yellow">✓</span><div><strong>Cuenta protegida</strong><small>{context.configured ? "Auth y RLS activos." : "Lista para conectar."}</small></div></article></div></div><div className="metrics-grid"><article className="metric-card"><span className="metric-icon purple">$</span><div className="metric-copy"><small>Ganado históricamente</small><strong>${context.wallet.lifetime.toLocaleString("es-AR")}</strong><em>Según el ledger</em></div></article><article className="metric-card"><span className="metric-icon blue">✓</span><div className="metric-copy"><small>Tareas confirmadas visibles</small><strong>{confirmed}</strong><em>Catálogo actual</em></div></article><article className="metric-card"><span className="metric-icon yellow">{context.profile.streakDays}</span><div className="metric-copy"><small>Racha actual</small><strong>{context.profile.streakDays} días</strong><em>Actividad consecutiva</em></div></article></div></section></AppShell>;
}
