import Link from "next/link";
import { PublicHeader } from "@/components/PublicHeader";

export default function HomePage() {
  return (
    <>
      <PublicHeader />
      <main>
        <section className="public-hero public-shell v4-hero">
          <div className="public-copy"><span className="eyebrow">TAREAS CLARAS. RECOMPENSAS TRANSPARENTES.</span><h1>Tu tiempo también <span>puede sumar.</span></h1><p>Completá encuestas, probá juegos y descubrí servicios. Antes de empezar vas a saber qué hacer, cuánto suma y cuándo se valida.</p><div className="public-actions"><Link href="/acceso" className="primary-button">Probar Gananza V5</Link><Link href="#como-funciona" className="secondary-button">Cómo funciona</Link></div><div className="hero-proof"><span>✓ Sin promesas engañosas</span><span>✓ Estados visibles</span><span>✓ Retiros simulados</span></div><p className="public-fine">Gananza no promete ingresos garantizados. Cada recompensa depende de completar y validar la tarea.</p></div>
          <div className="phone-stage" aria-label="Vista previa de Gananza"><div className="phone-glow"/><div className="phone-mock"><div className="phone-screen"><div className="phone-notch"/><div className="phone-mini-top"><span>9:41</span><b>GANANZA</b><i>●</i></div><div className="phone-greeting">Buenas noches<strong>Agustín</strong></div><div className="phone-balance"><small>DISPONIBLE PARA RETIRAR</small><strong>$8.650</strong><button>Retirar saldo</button></div><div className="phone-state-row"><span><i className="available"/>3 disponibles</span><span><i className="pending"/>1 pendiente</span></div><div className="phone-title">Tareas recomendadas</div><div className="phone-task"><i>KH</i><div><strong>Kingdom Harbor</strong><span>Llegá al nivel 12</span></div><b>+$4.200</b></div><div className="phone-task"><i style={{background:"linear-gradient(145deg,#2587e8,#123c8a)"}}>PO</i><div><strong>Hábitos digitales</strong><span>Encuesta de 8 minutos</span></div><b>+$950</b></div><div className="phone-task"><i style={{background:"linear-gradient(145deg,#f4b61f,#9b5e0c)",color:"#211500"}}>AP</i><div><strong>Probá AulaPro</strong><span>Registro gratuito</span></div><b>+$1.800</b></div><div className="phone-bottom"><span>⌂<small>Inicio</small></span><span>☑<small>Tareas</small></span><span>$<small>Billetera</small></span><span>○<small>Perfil</small></span></div></div></div></div>
        </section>

        <section className="trust-band"><div className="public-shell trust-band-grid"><div className="trust-item"><strong>Condiciones visibles</strong><span>Objetivo, plazo y recompensa antes de empezar.</span></div><div className="trust-item"><strong>Seis estados claros</strong><span>Desde disponible hasta confirmada o rechazada.</span></div><div className="trust-item"><strong>Retiros revisados</strong><span>Seguridad antes de liberar cada pago.</span></div></div></section>

        <section id="como-funciona" className="public-section public-shell"><div className="public-section-head"><span className="eyebrow">ASÍ FUNCIONA</span><h2>Elegí una tarea y seguí tu Gananza paso a paso.</h2><p>La interfaz está pensada para explicar qué ocurre con tu recompensa en cada momento.</p></div><div className="step-grid"><article className="step-card"><span>01</span><h3>Elegí</h3><p>Revisá el objetivo, el tiempo estimado, la vigencia y las condiciones.</p></article><article className="step-card"><span>02</span><h3>Completá</h3><p>Empezá desde Gananza y seguí el progreso sin perder la atribución.</p></article><article className="step-card"><span>03</span><h3>Validá</h3><p>La recompensa queda pendiente hasta que el proveedor confirma la acción.</p></article><article className="step-card"><span>04</span><h3>Retirá</h3><p>Cuando queda disponible, elegís el método y revisás la solicitud.</p></article></div></section>

        <section id="estados" className="public-section public-shell state-showcase"><div className="public-section-head"><span className="eyebrow">SIN SALDOS AMBIGUOS</span><h2>Cada tarea muestra su estado real.</h2></div><div className="state-cards"><article><i className="available"/><strong>Disponible</strong><span>Podés iniciarla ahora.</span></article><article><i className="progress"/><strong>En progreso</strong><span>Gananza guarda el seguimiento.</span></article><article><i className="pending"/><strong>Pendiente</strong><span>El proveedor está validando.</span></article><article><i className="done"/><strong>Confirmada</strong><span>Ya forma parte del saldo.</span></article><article><i className="rejected"/><strong>Rechazada</strong><span>Se informa el motivo y soporte.</span></article><article><i className="expired"/><strong>Finalizada</strong><span>La campaña terminó o agotó cupos.</span></article></div></section>

        <section className="public-cta public-shell"><div><span className="eyebrow">GANANZA V5 · SUPABASE READY</span><h2>Recorré el producto completo.</h2><p>Modo demo o datos reales con Auth, RLS, ledger, retiros y callbacks.</p></div><Link href="/acceso" className="primary-button">Abrir experiencia</Link></section>
      </main>
      <footer className="public-footer public-shell"><span>Gananza · Proyecto en validación</span><span>Argentina · 2026</span></footer>
    </>
  );
}
