-- Gananza V5 - initial secure schema
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated, service_role;

create type public.app_role as enum ('user', 'support', 'reviewer', 'admin');
create type public.offer_category as enum ('game', 'survey', 'app', 'service');
create type public.offer_status as enum ('draft', 'active', 'paused', 'ended');
create type public.task_session_status as enum ('opened', 'started', 'registered', 'pending', 'confirmed', 'rejected', 'reversed', 'expired');
create type public.conversion_status as enum ('pending', 'confirmed', 'rejected', 'reversed');
create type public.withdrawal_status as enum ('requested', 'reviewing', 'approved', 'paid', 'rejected', 'cancelled');
create type public.payout_method_type as enum ('mercado_pago', 'bank_transfer');
create type public.ticket_status as enum ('open', 'waiting_user', 'waiting_team', 'resolved', 'closed');
create type public.ticket_priority as enum ('low', 'normal', 'high', 'urgent');
create type public.fraud_flag_status as enum ('open', 'reviewing', 'resolved', 'dismissed');
create type public.fraud_severity as enum ('low', 'medium', 'high', 'critical');
create type public.ledger_entry_type as enum (
  'reward_pending', 'reward_confirmed', 'reward_rejected', 'reward_reversed',
  'withdrawal_hold', 'withdrawal_release', 'withdrawal_paid',
  'bonus', 'adjustment', 'debt_repayment'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  country_code text not null default 'AR' check (char_length(country_code) = 2),
  birth_date date,
  interests text[] not null default '{}',
  payout_preference public.payout_method_type not null default 'mercado_pago',
  onboarding_completed_at timestamptz,
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  level integer not null default 1 check (level >= 1),
  experience_points integer not null default 0 check (experience_points >= 0),
  streak_days integer not null default 0 check (streak_days >= 0),
  hide_balance boolean not null default false,
  notification_preferences jsonb not null default '{"tasks":true,"withdrawals":true,"support":true}'::jsonb,
  suspended_at timestamptz,
  suspension_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null default 'user',
  granted_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

create table public.providers (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null,
  website_url text,
  support_url text,
  is_active boolean not null default false,
  callback_mode text not null default 'generic_hmac_sha256',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table private.provider_credentials (
  provider_id uuid primary key references public.providers(id) on delete cascade,
  callback_secret text not null,
  signing_algorithm text not null default 'hmac-sha256',
  updated_at timestamptz not null default now()
);

create table public.offers (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete restrict,
  external_offer_id text not null,
  title text not null,
  brand text not null,
  description text not null default '',
  category public.offer_category not null,
  status public.offer_status not null default 'draft',
  country_codes text[] not null default array['AR']::text[],
  platform text not null default 'Web',
  reward_amount numeric(14,2) not null check (reward_amount >= 0),
  gross_amount numeric(14,2) not null check (gross_amount >= reward_amount),
  currency_code text not null default 'ARS' check (char_length(currency_code) = 3),
  estimated_minutes integer check (estimated_minutes > 0),
  validation_label text,
  difficulty_label text,
  badge_label text,
  instructions jsonb not null default '[]'::jsonb,
  requirements jsonb not null default '[]'::jsonb,
  tracking_url_template text,
  starts_at timestamptz,
  ends_at timestamptz,
  daily_cap integer check (daily_cap is null or daily_cap >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_id, external_offer_id)
);

create table public.task_sessions (
  id uuid primary key default gen_random_uuid(),
  offer_id uuid not null references public.offers(id) on delete restrict,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status public.task_session_status not null default 'opened',
  provider_click_id text,
  progress numeric(5,2) not null default 0 check (progress between 0 and 100),
  started_at timestamptz,
  registered_at timestamptz,
  completed_at timestamptz,
  last_provider_update_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, offer_id)
);

create table public.conversions (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete restrict,
  offer_id uuid references public.offers(id) on delete set null,
  task_session_id uuid references public.task_sessions(id) on delete set null,
  user_id uuid not null references public.profiles(id) on delete cascade,
  external_transaction_id text not null,
  status public.conversion_status not null default 'pending',
  gross_amount numeric(14,2) not null check (gross_amount >= 0),
  user_reward numeric(14,2) not null check (user_reward >= 0),
  currency_code text not null default 'ARS',
  raw_payload jsonb not null default '{}'::jsonb,
  confirmed_at timestamptz,
  rejected_at timestamptz,
  reversed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider_id, external_transaction_id)
);

create table public.wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  pending_balance numeric(14,2) not null default 0 check (pending_balance >= 0),
  available_balance numeric(14,2) not null default 0 check (available_balance >= 0),
  held_balance numeric(14,2) not null default 0 check (held_balance >= 0),
  withdrawn_balance numeric(14,2) not null default 0 check (withdrawn_balance >= 0),
  debt_balance numeric(14,2) not null default 0 check (debt_balance >= 0),
  lifetime_earned numeric(14,2) not null default 0 check (lifetime_earned >= 0),
  version bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table public.ledger_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  entry_type public.ledger_entry_type not null,
  pending_delta numeric(14,2) not null default 0,
  available_delta numeric(14,2) not null default 0,
  held_delta numeric(14,2) not null default 0,
  withdrawn_delta numeric(14,2) not null default 0,
  debt_delta numeric(14,2) not null default 0,
  conversion_id uuid references public.conversions(id) on delete set null,
  withdrawal_id uuid,
  idempotency_key text not null unique,
  description text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  check (pending_delta <> 0 or available_delta <> 0 or held_delta <> 0 or withdrawn_delta <> 0 or debt_delta <> 0)
);

create table public.payout_methods (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  method_type public.payout_method_type not null,
  label text not null,
  destination text not null,
  destination_masked text not null,
  holder_name text,
  is_default boolean not null default false,
  is_verified boolean not null default false,
  disabled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.withdrawals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  payout_method_id uuid not null references public.payout_methods(id) on delete restrict,
  amount numeric(14,2) not null check (amount > 0),
  currency_code text not null default 'ARS',
  status public.withdrawal_status not null default 'requested',
  idempotency_key text not null unique,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  paid_at timestamptz,
  rejection_reason text,
  provider_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ledger_entries
  add constraint ledger_entries_withdrawal_id_fkey foreign key (withdrawal_id) references public.withdrawals(id) on delete set null;

create table public.withdrawal_events (
  id bigint generated by default as identity primary key,
  withdrawal_id uuid not null references public.withdrawals(id) on delete cascade,
  from_status public.withdrawal_status,
  to_status public.withdrawal_status not null,
  note text,
  actor_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  task_session_id uuid references public.task_sessions(id) on delete set null,
  withdrawal_id uuid references public.withdrawals(id) on delete set null,
  subject text not null,
  category text not null default 'general',
  status public.ticket_status not null default 'open',
  priority public.ticket_priority not null default 'normal',
  assigned_to uuid references auth.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.support_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  author_id uuid not null references auth.users(id) on delete restrict,
  body text not null check (char_length(body) between 1 and 5000),
  is_internal boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  device_hash text not null,
  friendly_name text,
  platform text,
  first_ip inet,
  last_ip inet,
  country_code text,
  trusted_at timestamptz,
  blocked_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique(user_id, device_hash)
);

create table public.fraud_flags (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.profiles(id) on delete cascade,
  task_session_id uuid references public.task_sessions(id) on delete set null,
  withdrawal_id uuid references public.withdrawals(id) on delete set null,
  device_id uuid references public.devices(id) on delete set null,
  reason_code text not null,
  description text not null,
  severity public.fraud_severity not null default 'medium',
  score integer not null default 0 check (score between 0 and 100),
  status public.fraud_flag_status not null default 'open',
  metadata jsonb not null default '{}'::jsonb,
  reviewed_by uuid references auth.users(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  request_id text,
  ip_address inet,
  created_at timestamptz not null default now()
);

create table private.webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete restrict,
  external_event_id text not null,
  signature_valid boolean not null default false,
  payload jsonb not null,
  processing_status text not null default 'received',
  error_message text,
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(provider_id, external_event_id)
);

-- Index every ownership column used by RLS and common operational queries.
create index profiles_country_idx on public.profiles(country_code);
create index user_roles_user_idx on public.user_roles(user_id);
create index offers_status_country_idx on public.offers(status) include (country_codes);
create index task_sessions_user_idx on public.task_sessions(user_id, updated_at desc);
create index task_sessions_offer_idx on public.task_sessions(offer_id);
create index conversions_user_idx on public.conversions(user_id, created_at desc);
create index conversions_session_idx on public.conversions(task_session_id);
create index ledger_entries_user_idx on public.ledger_entries(user_id, created_at desc);
create index payout_methods_user_idx on public.payout_methods(user_id);
create unique index payout_methods_one_default_idx on public.payout_methods(user_id) where is_default and disabled_at is null;
create index withdrawals_user_idx on public.withdrawals(user_id, created_at desc);
create index withdrawals_status_idx on public.withdrawals(status, created_at);
create index support_tickets_user_idx on public.support_tickets(user_id, updated_at desc);
create index support_messages_ticket_idx on public.support_messages(ticket_id, created_at);
create index devices_user_idx on public.devices(user_id, last_seen_at desc);
create index fraud_flags_status_idx on public.fraud_flags(status, severity, created_at);

create or replace function private.set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function private.has_role(required_roles public.app_role[])
returns boolean language sql stable security definer set search_path = '' as $$
  select exists (
    select 1 from public.user_roles ur
    where ur.user_id = (select auth.uid()) and ur.role = any(required_roles)
  );
$$;

revoke all on function private.has_role(public.app_role[]) from public, anon, authenticated;
grant execute on function private.has_role(public.app_role[]) to authenticated, service_role;

create or replace function private.handle_new_user()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, display_name, country_code)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1), ''),
    coalesce(new.raw_user_meta_data ->> 'country_code', 'AR')
  ) on conflict (id) do nothing;
  insert into public.wallets (user_id) values (new.id) on conflict (user_id) do nothing;
  insert into public.user_roles (user_id, role) values (new.id, 'user') on conflict do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function private.prevent_financial_mutation()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  raise exception 'Financial history is append-only';
end;
$$;

create trigger ledger_entries_immutable before update or delete on public.ledger_entries for each row execute function private.prevent_financial_mutation();
create trigger audit_logs_immutable before update or delete on public.audit_logs for each row execute function private.prevent_financial_mutation();
create trigger withdrawal_events_immutable before update or delete on public.withdrawal_events for each row execute function private.prevent_financial_mutation();

create trigger profiles_updated_at before update on public.profiles for each row execute function private.set_updated_at();
create trigger providers_updated_at before update on public.providers for each row execute function private.set_updated_at();
create trigger offers_updated_at before update on public.offers for each row execute function private.set_updated_at();
create trigger task_sessions_updated_at before update on public.task_sessions for each row execute function private.set_updated_at();
create trigger conversions_updated_at before update on public.conversions for each row execute function private.set_updated_at();
create trigger payout_methods_updated_at before update on public.payout_methods for each row execute function private.set_updated_at();
create trigger withdrawals_updated_at before update on public.withdrawals for each row execute function private.set_updated_at();
create trigger support_tickets_updated_at before update on public.support_tickets for each row execute function private.set_updated_at();

-- RLS
alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.providers enable row level security;
alter table public.offers enable row level security;
alter table public.task_sessions enable row level security;
alter table public.conversions enable row level security;
alter table public.wallets enable row level security;
alter table public.ledger_entries enable row level security;
alter table public.payout_methods enable row level security;
alter table public.withdrawals enable row level security;
alter table public.withdrawal_events enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_messages enable row level security;
alter table public.devices enable row level security;
alter table public.fraud_flags enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_read_own on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy profiles_staff_read on public.profiles for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy roles_read_own on public.user_roles for select to authenticated using ((select auth.uid()) = user_id);
create policy roles_admin_all on public.user_roles for all to authenticated using ((select private.has_role(array['admin']::public.app_role[]))) with check ((select private.has_role(array['admin']::public.app_role[])));

create policy providers_read_active on public.providers for select to anon, authenticated using (is_active);
create policy providers_staff_all on public.providers for all to authenticated using ((select private.has_role(array['admin']::public.app_role[]))) with check ((select private.has_role(array['admin']::public.app_role[])));

create policy offers_read_active on public.offers for select to anon, authenticated using (status = 'active' and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now()));
create policy offers_staff_all on public.offers for all to authenticated using ((select private.has_role(array['admin']::public.app_role[]))) with check ((select private.has_role(array['admin']::public.app_role[])));

create policy sessions_read_own on public.task_sessions for select to authenticated using ((select auth.uid()) = user_id);
create policy sessions_staff_read on public.task_sessions for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy conversions_read_own on public.conversions for select to authenticated using ((select auth.uid()) = user_id);
create policy conversions_staff_read on public.conversions for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy wallets_read_own on public.wallets for select to authenticated using ((select auth.uid()) = user_id);
create policy wallets_staff_read on public.wallets for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy ledger_read_own on public.ledger_entries for select to authenticated using ((select auth.uid()) = user_id);
create policy ledger_staff_read on public.ledger_entries for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy payout_methods_own on public.payout_methods for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy payout_methods_staff_read on public.payout_methods for select to authenticated using ((select private.has_role(array['reviewer','admin']::public.app_role[])));

create policy withdrawals_read_own on public.withdrawals for select to authenticated using ((select auth.uid()) = user_id);
create policy withdrawals_staff_read on public.withdrawals for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));
create policy withdrawal_events_read_own on public.withdrawal_events for select to authenticated using (exists (select 1 from public.withdrawals w where w.id = public.withdrawal_events.withdrawal_id and w.user_id = (select auth.uid())));
create policy withdrawal_events_staff_read on public.withdrawal_events for select to authenticated using ((select private.has_role(array['support','reviewer','admin']::public.app_role[])));

create policy tickets_own_select on public.support_tickets for select to authenticated using ((select auth.uid()) = user_id);
create policy tickets_own_insert on public.support_tickets for insert to authenticated with check ((select auth.uid()) = user_id);
create policy tickets_staff_all on public.support_tickets for all to authenticated using ((select private.has_role(array['support','admin']::public.app_role[]))) with check ((select private.has_role(array['support','admin']::public.app_role[])));

create policy messages_own_select on public.support_messages for select to authenticated using (exists (select 1 from public.support_tickets t where t.id = public.support_messages.ticket_id and t.user_id = (select auth.uid())) and not public.support_messages.is_internal);
create policy messages_own_insert on public.support_messages for insert to authenticated with check (public.support_messages.author_id = (select auth.uid()) and not public.support_messages.is_internal and exists (select 1 from public.support_tickets t where t.id = public.support_messages.ticket_id and t.user_id = (select auth.uid())));
create policy messages_staff_all on public.support_messages for all to authenticated using ((select private.has_role(array['support','admin']::public.app_role[]))) with check ((select private.has_role(array['support','admin']::public.app_role[])));

create policy devices_own on public.devices for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy devices_staff_read on public.devices for select to authenticated using ((select private.has_role(array['reviewer','admin']::public.app_role[])));

create policy fraud_staff_only on public.fraud_flags for all to authenticated using ((select private.has_role(array['reviewer','admin']::public.app_role[]))) with check ((select private.has_role(array['reviewer','admin']::public.app_role[])));
create policy audit_admin_read on public.audit_logs for select to authenticated using ((select private.has_role(array['admin']::public.app_role[])));

-- Explicit privileges. Mutations to financial tables only happen through RPC functions.
revoke all on all tables in schema public from anon, authenticated;
grant select on public.providers, public.offers to anon, authenticated;
grant select on public.profiles, public.user_roles, public.task_sessions, public.conversions, public.wallets, public.ledger_entries,
  public.payout_methods, public.withdrawals, public.withdrawal_events, public.support_tickets, public.support_messages,
  public.devices, public.fraud_flags, public.audit_logs to authenticated;
grant update (display_name, country_code, birth_date, interests, payout_preference, onboarding_completed_at, hide_balance, notification_preferences) on public.profiles to authenticated;
grant insert (user_id, method_type, label, destination, destination_masked, holder_name, is_default) on public.payout_methods to authenticated;
grant update (label, destination, destination_masked, holder_name, is_default, disabled_at) on public.payout_methods to authenticated;
grant delete on public.payout_methods to authenticated;
grant usage, select on all sequences in schema public to authenticated, service_role;
grant all on all tables in schema public to service_role;
grant all on all tables in schema private to service_role;
