import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { Icon } from "@/components/Icons";
import { StatusPill } from "@/components/StatusPill";
import { getAppContext, getCatalogTasks, getLedgerMovements } from "@/lib/gananza/server-data";

const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });

export default async function DashboardPage() {
  const [context, tasks, movements] = await Promise.all([getAppContext(), getCatalogTasks(), getLedgerMovements()]);
  const recommended = tasks.filter((task) => ["available", "in_progress", "pending"].includes(task.status)).slice(0, 3);
  const availableCount = tasks.filter((task) => task.status === "available").length;
  const pendingCount = tasks.filter((task) => task.status === "pending").length;
  const firstName = context.profile.displayName.split(" ")[0] || "Usuario";
  return <AppShell active="/dashboard"><section className="page-content"><div className="v3-page-heading"><div><span className="eyebrow">GANANZA V5 · {context.configured ? "DATOS REALES" : "MODO DEMO"}</span><h1>Buenas noches, {firstName}.</h1><p>Tenés {availableCount} tareas disponibles{pendingCount ? ` y ${pendingCount} recompensa en validación` : ""}.</p></div><Link href="/tareas" className="primary-button">Explorar tareas</Link></div>
    <div className="hero-grid"><article className="balance-card"><div className="balance-card-top"><span className="card-label">SALDO DISPONIBLE</span><span className="secure-balance">✓ CONFIRMADO</span></div><strong className="big-balance">{context.profile.hideBalance ? "••••••" : money.format(context.wallet.available)}</strong><p>Confirmado y listo para solicitar</p><div className="balance-actions"><Link href="/retiros">Retirar</Link><Link href="/tareas">Sumar más</Link></div></article><div className="hero-side"><article className="pending-card"><div className="pending-card-head"><span>SALDO PENDIENTE</span><i /></div><strong>{context.profile.hideBalance ? "••••" : money.format(context.wallet.pending)}</strong><p>{pendingCount} {pendingCount === 1 ? "tarea" : "tareas"} en validación</p><div className="pending-track"><span style={{ width: pendingCount ? "64%" : "0%" }} /></div><Link href="/tareas" className="inline-detail">Ver estado →</Link></article><article className="streak-card"><div className="streak-head"><span>RACHA ACTUAL</span><span style={{color:"var(--purple-2)"}}>actividad</span></div><div className="streak-number"><strong>{context.profile.streakDays}</strong><span>días seguidos</span></div><div className="week-row">{["L","M","X","J","V","S","D"].map((day, index) => <span key={day} className={`week-day ${index < Math.min(context.profile.streakDays, 3) ? "done" : index === Math.min(context.profile.streakDays, 3) ? "today" : ""}`}>{day}</span>)}</div></article></div></div>
    <div className="metrics-grid"><article className="metric-card"><span className="metric-icon purple"><Icon name="trend" /></span><div className="metric-copy"><small>Ganado históricamente</small><strong>{money.format(context.wallet.lifetime)}</strong><em>Ledger auditable</em></div></article><article className="metric-card"><span className="metric-icon blue"><Icon name="clock" /></span><div className="metric-copy"><small>Tareas visibles</small><strong>{tasks.length}</strong><em>{availableCount} disponibles</em></div></article><article className="metric-card"><span className="metric-icon yellow"><Icon name="star" /></span><div className="metric-copy"><small>Nivel actual</small><strong>{context.profile.level}</strong><em>{context.profile.experiencePoints.toLocaleString("es-AR")} puntos</em></div></article></div>
    <div className="dashboard-grid"><section className="section-card"><div className="section-head"><div><span className="eyebrow">RECOMENDADAS PARA VOS</span><h2>Tareas y seguimientos</h2><p>Disponibles, en curso y pendientes en un mismo lugar.</p></div><Link className="section-link" href="/tareas">Ver todas →</Link></div><div className="task-list">{recommended.length ? recommended.map((task) => { const kind=task.category==="Juegos"?"game":task.category==="Encuestas"?"survey":"service"; return <article className="task-row" key={task.id}><div className={`task-art ${kind}`}><Icon name={kind === "game" ? "game" : kind === "survey" ? "survey" : "service"} size={23}/></div><div className="task-copy"><div className="task-meta"><StatusPill status={task.status}/><span>{task.time} · {task.platform}</span></div><h3>{task.brand}</h3><p>{task.description}</p>{typeof task.progress === "number" && <div className="mini-progress"><span style={{width:`${task.progress}%`}}/></div>}</div><div className="task-reward"><small>RECOMPENSA</small><strong>{money.format(task.reward)}</strong><Link href="/tareas" className="task-button">{task.status === "available" ? "Ver tarea" : task.status === "in_progress" ? "Continuar" : "Ver estado"}</Link></div></article>; }) : <div className="empty-state compact"><h3>No hay tareas disponibles</h3><p>El catálogo se actualizará cuando existan campañas para tu perfil.</p></div>}</div></section><aside className="section-card"><div className="section-head"><div><span className="eyebrow">ACTIVIDAD RECIENTE</span><h2>Movimientos</h2></div></div><div className="activity-list">{movements.slice(0,5).map((item:any)=><div className="activity-item" key={item.id}><span><Icon name={item.amount < 0 ? "withdraw" : item.state.startsWith("Pend") ? "clock" : "verified"} size={17}/></span><div><strong>{item.label}</strong><small>{item.date}</small></div><b className={item.amount >= 0 ? "positive" : ""}>{item.amount >= 0 ? "+" : "−"}{money.format(Math.abs(item.amount))}</b></div>)}{!movements.length && <p className="empty-copy">Todavía no hay movimientos.</p>}</div></aside></div>
  </section></AppShell>;
}
